# Operator development deployment.
# Assumes that the last released operator is deployed initially and that
# it started the registry registry.default.svc.cluster.local
apiVersion: skaffold/v1
kind: Config
metadata:
  name: image-registry-operator
build:
  artifacts:
  - image: registry.default.svc.cluster.local/image-registry-operator
    context: .
    docker:
      dockerfile: build/Dockerfile
      target: operator
deploy:
  kustomize:
    path: deploy/dev
