apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: imageregistries.registry.mgoltzsche.github.com
spec:
  group: registry.mgoltzsche.github.com
  names:
    kind: ImageRegistry
    listKind: ImageRegistryList
    plural: imageregistries
    singular: imageregistry
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ImageRegistry is the Schema for the imageregistries API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ImageRegistrySpec defines the desired state of ImageRegistry
          properties:
            auth:
              description: AuthSpec specifies the CA certificate and optional docker_auth
                ConfigMap name
              properties:
                ca:
                  description: CertificateSpec refers to a secret and an optional
                    issuer to generate it
                  properties:
                    issuerRef:
                      description: CertificateIssuerSpec refers to a certificate issuer
                      properties:
                        kind:
                          type: string
                        name:
                          type: string
                      required:
                      - kind
                      - name
                      type: object
                    secretName:
                      type: string
                  type: object
                configMapName:
                  type: string
              required:
              - ca
              type: object
            persistentVolumeClaim:
              description: PersistentVolumeClaimSpec specifies the PersistentVolumeClaim
                that should be maintained
              properties:
                accessModes:
                  items:
                    type: string
                  type: array
                deleteClaim:
                  type: boolean
                resources:
                  description: ResourceRequirements describes the compute resource
                    requirements.
                  properties:
                    limits:
                      additionalProperties:
                        type: string
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      additionalProperties:
                        type: string
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                  type: object
                storageClassName:
                  type: string
              type: object
            replicas:
              format: int32
              type: integer
            tls:
              description: CertificateSpec refers to a secret and an optional issuer
                to generate it
              properties:
                issuerRef:
                  description: CertificateIssuerSpec refers to a certificate issuer
                  properties:
                    kind:
                      type: string
                    name:
                      type: string
                  required:
                  - kind
                  - name
                  type: object
                secretName:
                  type: string
              type: object
          required:
          - persistentVolumeClaim
          type: object
        status:
          description: ImageRegistryStatus defines the observed state of ImageRegistry
          properties:
            conditions:
              additionalProperties:
                description: "Condition represents an observation of an object's state.
                  Conditions are an extension mechanism intended to be used when the
                  details of an observation are not a priori known or would not apply
                  to all instances of a given Kind. \n Conditions should be added
                  to explicitly convey properties that users and components care about
                  rather than requiring those properties to be inferred from other
                  observations. Once defined, the meaning of a Condition can not be
                  changed arbitrarily - it becomes part of the API, and has the same
                  backwards- and forwards-compatibility concerns of any other part
                  of the API."
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    description: ConditionReason is intended to be a one-word, CamelCase
                      representation of the category of cause of the current status.
                      It is intended to be used in concise output, such as one-line
                      kubectl get output, and in summarizing occurrences of causes.
                    type: string
                  status:
                    type: string
                  type:
                    description: "ConditionType is the type of the condition and is
                      typically a CamelCased word or short phrase. \n Condition types
                      should indicate state in the \"abnormal-true\" polarity. For
                      example, if the condition indicates when a policy is invalid,
                      the \"is valid\" case is probably the norm, so the condition
                      should be called \"Invalid\"."
                    type: string
                required:
                - status
                - type
                type: object
              description: Conditions is a set of Condition instances.
              type: array
            hostname:
              type: string
            observedGeneration:
              format: int64
              type: integer
            tlsSecretName:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
