apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: imageregistryaccounts.registry.mgoltzsche.github.com
spec:
  group: registry.mgoltzsche.github.com
  names:
    kind: ImageRegistryAccount
    listKind: ImageRegistryAccountList
    plural: imageregistryaccounts
    singular: imageregistryaccount
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ImageRegistryAccount is the Schema for the imageregistryaccounts
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ImageRegistryAccountSpec defines the desired state of ImageRegistryAccount
          properties:
            labels:
              additionalProperties:
                items:
                  type: string
                type: array
              description: Labels to match against authorization rules
              type: object
            password:
              description: bcrypt hashed password
              type: string
            ttl:
              type: string
          required:
          - password
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
