resources:
- crds/registry.mgoltzsche.github.com_imagepullsecrets_crd.yaml
- service_account.yaml
- role.yaml
- role_binding.yaml
- operator.yaml
- registry-ca-cluster-issuer.yaml
#- skaffold-kaniko-podpreset.yaml

namespace: build
