apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-registry-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: image-registry-operator
  template:
    metadata:
      labels:
        name: image-registry-operator
    spec:
      serviceAccountName: image-registry-operator
      containers:
        - name: operator
          image: mgoltzsche/image-registry-operator:latest
          command:
          - image-registry-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "image-registry-operator"
            - name: OPERATOR_DNS_ZONE
              value: svc.example.org
            - name: OPERATOR_DEFAULT_CLUSTER_ISSUER
              value: registry-ca-issuer
      imagePullSecrets:
      - name: registry-deployment-pull-credentials
