apiVersion: apps/v1
kind: Deployment
metadata:
  name: credential-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: credential-manager
  template:
    metadata:
      labels:
        name: credential-manager
    spec:
      serviceAccountName: credential-manager
      containers:
        - name: credential-manager
          image: registry.example.org/credential-manager
          command:
          - credential-manager
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "credential-manager"
      imagePullSecrets:
      - name: registry-deployment-pull-credentials