apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: image-registry
rules:
- apiGroups:
  - registry.mgoltzsche.github.com
  resources:
  - imageregistryaccounts
  verbs:
  - get
  - list
  - watch
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-registry
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: image-registry
  apiGroup: rbac.authorization.k8s.io
