kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: credential-manager
subjects:
- kind: ServiceAccount
  name: credential-manager
roleRef:
  kind: Role
  name: credential-manager
  apiGroup: rbac.authorization.k8s.io
