kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-registry-operator
subjects:
- kind: ServiceAccount
  name: image-registry-operator
  namespace: image-registry-operator
roleRef:
  kind: ClusterRole
  name: image-registry-operator
  apiGroup: rbac.authorization.k8s.io
